// API "adder": Application Media Types
//
// Code generated by goagen v1.1.0-dirty, DO NOT EDIT.
//
// Command:
// $ goagen
// --design=github.com/gotoolkit/api/design
// --out=$(GOPATH)/src/github.com/gotoolkit/api
// --version=v1.0.0

package app
